### ISSUE TITLE
Buffer becomes empty when called repeatedly

### ISSUE THREAD

**Issue by sarg** [agzam/exwm-edit#16]
Given that I have some text entered in textarea, if I do `C-c '` (exwm-edit buffer opens) then `C-c C-k` (the buffer closes) then again `C-c '` - the edit buffer becomes empty. It happens because the condition `(string= exwm-kill-ring-car exwm-edit-last-kill)` in `exwm-edit--yank` evaluates to true and the yank doesn't happen.

To fix the issue I've added `(setq exwm-edit-last-kill nil)` to finish and cancel functions.

**Comment by walseb** [comment]
If I remember correctly I had a pretty good reason for introducing this ugly hack. Since you have been using this for ~20 days now, have you seen any negative side effects from doing this? Otherwise it might be worthwhile to just remove the last kill stuff all together

**Comment by walseb** [comment]
Oh yeah now I remember. The problem is that if the text area you are selecting is empty, it can't copy anything new from that text box which means the last kill doesn't get removed from the kill ring, and then when it goes over and pastes the last kill to the exwm-edit buffer it would just paste the last kill even if the text box was empty. And I couldn't find a way to detect weather or not the selected text box is empty besides this ugly hack or an even uglier hack, where I would insert a space into every text box before copying and then remove it once it reaches the exwm-edit buffer. This solution has been pretty unreliable though but atleast it works sometimes as opposed to never. But maybe it would be better to have more predictable behavior where you always have the last kill in the exwm-edit buffer, even if the text box was empty.
