### ISSUE TITLE
Maintainer(s) needed

### ISSUE THREAD

**Issue by agzam** [agzam/exwm-edit#18]
I am currently not using EXWM and consequently can't address issues and PRs quickly. If someone would like to step in, please let me know.

**Comment by walseb** [comment]
Sorry I forgot about this issue until I created the PR. I would be fine with maintaining this package since I have begun using it again, although for me the current situation is fine where I can create PRs and comment. But if you want me to I can take the responsibility of accepting new PRs and such if you don't want to have to evaluate PRs when you don't even use the package.

**Comment by agzam** [comment]
Oh wow. That'd be awesome. The package is small and should't require too much of your attention. The only reason I'm asking for help, because I cannot quickly test things out in a timely manner, and I don't want folks to get frustrated by the slow process. I can still review the code and participate in discussing issues/new features, etc.

I have invited you as a collaborator, I'll give you admin rights once you accept it.

Thank you for volunteering.
