### ISSUE TITLE
Works with Jupyter notebook

### ISSUE THREAD

**Issue by zackteo** [agzam/exwm-edit#21]
I don't think this is a use case most people go to for, but just wanted to say I was pleasantly surprised when this just worked with editing jupyter notebook! :D

**Comment by walseb** [comment]
Cool! There are a few text-boxes that I have noticed don't work too well because they are slow which messes with the timers (for example discord), but usually if it's outside of the browser it should be fine. I'll close this now but maybe this should be added to the readme or something. Feel free to make a PR if you wish
