### ISSUE TITLE
Does not copy when nothing is selected

### ISSUE THREAD

**Issue by agzam** [agzam/exwm-edit#4]
If in the text-area nothing is selected (marked) and you press `C-c C-'` - sometimes it won't grab the content. And as a result - nothing gets pasted into the exwm-edit buffer. Even worse - it sometimes grabs the latest item in the kill ring (which most often is absolutely unrelated to the text you are trying to edit) and pastes that into exwm-edit buffer. That is really annoying. 

I can't simply find absolutely guaranteed way to determine if anything is selected in GUI windows or not. `(gui-get-selection 'PRIMARY 'STRING)` (when nothing is selected) - returns whatever previously was copied to the clipboard. That thing should return `nil` when nothing is selected in GUI, but it doesn't.
And it's not even guaranteed to always return the last thing in the clipboard - so just comparing what it returns and what's in the clipboard has not 100% success rate either.

**Comment by DamienCassou** [comment]
I confirm the problem, this is annoying.

**Comment by agzam** [comment]
should be fixed in https://github.com/agzam/exwm-edit/commit/847a9079c4ad658d3eda356a7b9e74c11718cd7c

**Comment by agzam** [comment]
nope... it did not fix it ;(

**Comment by DamienCassou** [comment]
Thank you very much for your help. I will try updating exwm and exwm-edit.

**Comment by walseb** [comment]
The problem seems to be that `gui-get-selection` doesn't work properly if run right after marking the text. This is probably why it works fine if you manually select part of the text with your mouse and then run it. It's a lot more reliable if you use C-c instead, but that also has the problem of not working if the search box is empty. I will see if I can get it to work reliably this weekend

**Comment by agzam** [comment]
@walseb that would be awesome. Sorry, I tried different ways, but still couldn't make it work reliably.

**Comment by spiderbit** [comment]
@walseb I just tested your branch I can't compare it to the git master from here but with the latest melpa version, and yes it works (more) reliable when you change text in edit mode and commit it but it has still 2 problems:

1. if you have a empty text field and go into edit-mode it goes crazy copies the last thing that was in the kill ring
2. if you press 1 time in the edit buffer C-c C-k you have to delete all text in the text field that it resets otherwise it's completly bugged.

But as long as you don't have a empty text field and never press C-c C-k in edit mode it seems to work fine :D

**Comment by walseb** [comment]
Yeah I noticed the problem mentioned in point 1 but haven't found a simple solution to it yet. I think it worked better for me before because I was using a very slow laptop. I will have to look into point 2 later because I haven't noticed it before. The problem is that I haven't been using firefox that often after I managed to get eww/w3m to replace the documentation browsing role in my workflow but I will look into fixing up the patch later. Maybe I should make it optional to carry over the contents of the text box to emacs since that's where all the problems lie? Thanks for testing anyways! Also melpa should have the latest git version.
