### ISSUE TITLE
Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by 11111000000** [agzam/exwm-edit#7]
`C-c ,`
Wrong type argument: stringp, nil

**Comment by agzam** [comment]
Can you provide more info how to re-produce this?

**Comment by Sbozzolo** [comment]
Same problem here.

Config:
```elisp
(use-package exwm-edit)
```
Emacs version: `GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.1) of 2019-04-04`
Version of EXWM `0.22.1`.
Distro: Gentoo

How to reproduce:
1. Open Chromium
2. Visit, e.g., duckduckgo.com
3. Focus on search bar
4. Invoke `C-c '`
5. Get the error: `menu-bar-update-yank-menu: Wrong type argument: stringp, nil`

**Comment by Ambrevar** [comment]
Same here.  If I comment out `kill-new` in exwm-edit--compose it works.
The bug is not always triggered, but I can't fathom why.

**Comment by Ambrevar** [comment]
Another possibly solution: call `gui-get-selection` twice.  Not sure why it works though:

```
(let ((sel (and (gui-get-selection)
                (gui-get-selection))))
  (kill-new sel)
  (insert sel))
```

**Comment by walseb** [comment]
Yeah `gui-get-selection` is very unreliable and if you call it while not having a selection you usually get back your last selection which is why the compose function currently doesn't copy over your text if you open fields with the same contents twice in a row. I haven't tried calling `gui-get-selection` though so that might be worth looking into. I don't remember what `kill-new` is doing there but im pretty sure it was important
